quarkus.http.port=8084

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mysql123
quarkus.datasource.jdbc.url=jdbc:mysql://mysql-local:3306/seguridad_exa

quarkus.hibernate-orm.database.generation=update

quarkus.smallrye-health.root-path=/q/health
