quarkus.config.locations=file:/app/central-config/common.properties,file:/app/central-config/ms-hotel.properties

quarkus.application.name=ms-hotel
quarkus.consul-config.enabled=false
quarkus.http.host=0.0.0.0
